# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_categoria_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Concluído'), ('CD', 'Cancelada')], default='', max_length=5, verbose_name='Status'),
        ),
    ]
